DjangoAdmin/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),    
    path('',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
]
 

employee/models.py
from django.db import models

# Create your models here.
 
class Employee(models.Model):  
    eid = models.IntegerField()  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee"  

employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

employee/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse 
from employee.forms import EmployeeForm  
from employee.models import Employee
import datetime

# Create your views here.

def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  

def show(request):
    employees = Employee.objects.all().order_by('eid')
    calendar = {
        'day': (datetime.datetime.now()).strftime("%d"),
        'month': (datetime.datetime.now()).strftime("%B"),
        'year': (datetime.datetime.now()).strftime("%Y")
    }

    time = {
        'hour': (datetime.datetime.now()).strftime("%I"),
        'minute': (datetime.datetime.now()).strftime("%M"),
        'midday': (datetime.datetime.now()).strftime("%p")
    }
    

    return render(request,"show.html",{'employees':employees,'calendar': calendar, 'time': time}) 

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/")  
    return render(request, 'edit.html', {'employee': employee})  

def search(request, id):
    form =  Employee.objects.get(id=id)
    print(frorm)  

def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/")

employee/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Update</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
       body{
            font-family: monospace;
            font-size: 2em;
            font-weight: bold;
            text-align: center;
      }  

      h2 {
        font-weight: bold;
      }

      .main {
        margin-top: 100px;
      }

      .details {
        padding: 10px;
        margin-left: 250px;
      }

      .text {
        margin: 0 15px 0 250px;
        display: inline;
        white-space: nowrap
      }

      .inp {
        margin-left: 50px;
      }
    </style>
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
    {% csrf_token %}
    <div class="main container">  
      <br>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="details col-sm-4">  
          <h2>Update Details:</h2>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Id:</label>  
        <div class="inp col-sm-4">  
          <input type="text" name="eid" id="id_eid" required maxlength="255" value="{{ employee.eid }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Name:</label>  
        <div class="inp col-sm-4">  
          <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Email:</label>  
        <div class="inp col-sm-4">  
          <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Contact:</label>  
        <div class="inp col-sm-4">  
          <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="details col-sm-4">  
          <button type="submit" class="btn btn-outline-success">Update</button>  
        </div>  
      </div>  
    </div>         
</form>  
</body>  
</html>  

employee/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">  
    <style>
      body{
        font-family: monospace;
        font-size: 2em;
        /* font-size: larger; */
        font-weight: bold;
        text-align: center;
      }

      h2 {
        font-weight: bold;
      }

      .main {
        margin-top: 100px;
      }

      .details {
        padding: 10px;
        margin-left: 250px;
      }

      .text {
        margin: 0 15px 0 250px;
        display: inline;
        white-space: nowrap
      }

      .inp {
        padding-left: 10px;
        margin-left: 50px;
      }
    </style>
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
      {% csrf_token %}  
    <div class="main container">  
      <br>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="details col-sm-4">  
          <h2>Enter Details:</h2>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Id:</label>  
        <div class="inp col-sm-4">  
          {{ form.eid }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Name:</label>  
        <div class="inp col-sm-4">  
          {{ form.ename }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Email:</label>  
        <div class="inp col-sm-4">  
          {{ form.eemail }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="text col-sm-2 col-form-label">Employee Contact:</label>  
        <div class="inp col-sm-4">  
          {{ form.econtact }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="details col-sm-4">  
          <button type="submit" class="btn btn-outline-success">Submit</button>  
        </div>  
      </div>  
    </div>  
</form>  
</body>  
</html>  

employee/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">         
    <style>
    body{
        font-family: monospace;
        font-size: x-large;
        text-align: center;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }    
        
    .main {
        /* border: 2px solid black; */
        margin: 30px 0 30px 0;
        width: 60%;
    }

    .table {
        /* border: 2px solid black; */
        border-radius: 5px;
        width: 60%;
        margin: 10px auto;
    }

    .date, .title, .time  {
        border: 5px solid #2b324d;
        color: #2b324d;
        padding: 10px;
    }
    

    </style>
</head>  
<body> 
    <div class="main d-flex flex-row bd-highlight justify-content-between">
        <div class="date">
            {% if calendar.day == 1 or calendar.day == 31 %}
                <h2 class="top left">{{ calendar.day }}st {{ calendar.month }},{{ calendar.year}}</h2>
            {% elif calendar.day == 2 %}
                <h2 class="top left">{{ calendar.day }}nd {{ calendar.month }},{{ calendar.year}}</h2>
            {% elif calendar.day == 3 %}
                <h2 class="top left">{{ calendar.day }}rd {{ calendar.month }},{{ calendar.year}}</h2>
            {% else %}
                <h2 class="top left">{{ calendar.day }}th {{ calendar.month }},{{ calendar.year}}</h2>
            {% endif %}
        </div>
        <div class="title">
            <h2>Dashboard</h2>    
        </div>
        <div class="time">
            <h2>{{ time.hour }} : {{ time.minute }}  {{ time.midday }}</h2>
        </div>
    </div>
    
    <table class="table table-striped table-bordered table-sm">  
        <thead class="thead-dark">  
        <tr>  
            <th>Employee ID</th>  
            <th>Employee Name</th>  
            <th>Employee Email</th>  
            <th>Employee Contact</th>  
            <th>Actions</th>  
        </tr>  
        </thead>  
        <tbody>  
        {% for employee in employees %}  
        <tr>  
            <td>{{ employee.eid }}</td>  
            <td>{{ employee.ename }}</td>  
            <td>{{ employee.eemail }}</td>  
            <td>{{ employee.econtact }}</td>  
            <td>  
                <a class='btn btn-outline-warning btn-sm' href="/edit/{{ employee.id }}">Edit</a> |
                <a class='btn btn-outline-danger btn-sm' href="/delete/{{ employee.id }}">Delete</a>  
            </td>  
        </tr>  
        {% endfor %}  
        </tbody>  
    </table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-outline-primary">Add New Record</a></center> 
</body>  
</html> 